import type { FormEvent } from "react";
import { useEffect, useState } from "react";
import { Activity, ArrowLeft, Bell, Brain, CalendarDays, ChartNoAxesCombined, CircleUser, ClipboardList, Eye, EyeOff, HeartPulse, History, Home, LayoutDashboard, LoaderCircle, LogOut, MapPinned, Menu, Settings, Timer, TrendingUp, TriangleAlert, Users, X } from "lucide-react";
import { embeddedScreens } from "./embeddedScreens";
import { appendPatientCsv, fetchAlerts, fetchDashboard, fetchHealth, fetchInsights, fetchRecords, login, requestPasswordReset, resetPassword, signup, uploadPatientCsv } from "./api";
import type { Alert, DashboardSummary, Insight, PatientRecord } from "./types";

const screens = embeddedScreens;
const getUser = () => JSON.parse(localStorage.getItem("d2a_user") || "null") as { name?: string; email?: string; role?: string; health_center?: string; dataset_ready?: boolean } | null;

export function HtmlScreens() {
  const [activeId, setActiveId] = useState(() => window.location.hash.slice(1) || (getUser() ? "dashboard" : "landing"));
  useEffect(() => { const change = () => setActiveId(window.location.hash.slice(1) || "dashboard"); window.addEventListener("hashchange", change); return () => window.removeEventListener("hashchange", change); }, []);
  const user = getUser();
  useEffect(() => { if (activeId === "dashboard" && user && !user.dataset_ready && !localStorage.getItem("d2a_has_uploaded_data")) window.location.hash = "upload"; }, [activeId, user]);
  if (activeId === "signup") return <SignupScreen />;
  if (activeId === "login") return <LoginScreen />;
  if (activeId === "forgot-password") return <ForgotPasswordScreen />;
  if (activeId === "reset-password") return <ResetPasswordScreen />;
  if (activeId === "upload") return <UploadScreen />;
  if (activeId === "landing") return <LandingScreen />;
  if (activeId === "settings") return <SettingsScreen />;
  const livePages = ["dashboard", "alerts", "ai-insights", "history", "patient-history", "patterns", "surge-forecast", "regional-rankings"];
  if (livePages.includes(activeId)) return <LiveDataScreen screen={activeId} />;
  const page = screens.find(([id]) => id === activeId) || screens[0];
  return <main className="html-screen-host"><iframe className="html-screen-frame" srcDoc={page[2]} title={page[1]} /></main>;
}

function LandingScreen() {
  return <main className="landing-page">
    <header className="landing-header">
      <a className="landing-brand" href="#landing" aria-label="D2A home"><HeartPulse size={29} strokeWidth={3} /><span>D2A</span><small>Health Intelligence</small></a>
      <nav className="landing-nav" aria-label="Main navigation"><a href="#landing">Overview</a><a href="#login">Sign in</a><a className="landing-nav-button" href="#signup">Create account</a></nav>
    </header>
    <section className="landing-hero">
      <div className="landing-copy">
        <span className="landing-eyebrow"><Activity size={16} /> Data-to-action health intelligence</span>
        <h1>See health risks sooner. <em>Act with confidence.</em></h1>
        <p className="landing-lede">D2A helps health centers turn anonymized visit data into clear disease patterns, early warnings, and practical next steps for teams in the field.</p>
        <div className="landing-actions"><a className="primary-action" href="#signup">Start with your data <TrendingUp size={17} /></a><a className="secondary-action" href="#login">Sign in to D2A</a></div>
        <div className="landing-trust"><span><HeartPulse size={17} /> Built for health-center teams</span><span><TriangleAlert size={16} /> Decisions remain human-led</span></div>
      </div>
      <div className="landing-visual" aria-label="D2A health intelligence preview">
        <img className="landing-team-image" src="https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?auto=format&fit=crop&w=1100&q=82" alt="Healthcare team reviewing patient data" />
        <div className="preview-heading"><div><span className="preview-kicker">LIVE DATA VIEW</span><strong>District health overview</strong></div><span className="preview-status"><i /> Connected</span></div>
        <div className="preview-metrics"><div><span>Visits this week</span><strong>674</strong><small className="positive">+18.4%</small></div><div><span>Active signals</span><strong>04</strong><small className="warning-text">Needs review</small></div></div>
        <div className="preview-chart"><div className="preview-chart-title"><strong>Cases over time</strong><span>Last 8 weeks</span></div><div className="preview-graph"><span className="graph-line" /><span className="graph-point point-one" /><span className="graph-point point-two" /><span className="graph-point point-three" /><span className="graph-point point-four" /></div><div className="preview-axis"><span>W18</span><span>W20</span><span>W22</span><span>W24</span></div></div>
        <div className="preview-alert"><span className="preview-alert-icon"><TriangleAlert size={17} /></span><div><strong>Malaria signal detected</strong><span>Gasabo · 2.4x above baseline</span></div><a href="#login" aria-label="Review health signal">Review <TrendingUp size={15} /></a></div>
      </div>
    </section>
    <section className="landing-features"><div><span className="feature-icon teal"><ChartNoAxesCombined size={19} /></span><h2>Patterns you can see</h2><p>Track disease trends, patient volume, villages, and facilities from one live view.</p></div><div><span className="feature-icon blue"><TriangleAlert size={19} /></span><h2>Warnings with evidence</h2><p>Understand what changed, how confident the signal is, and what supports it.</p></div><div><span className="feature-icon orange"><HeartPulse size={19} /></span><h2>Advice that moves teams</h2><p>Give doctors, nurses, and health officials practical mitigation steps and outreach actions.</p></div></section>
  </main>;
}

function LiveDataScreen({ screen }: { screen: string }) {
  const [dashboard, setDashboard] = useState<DashboardSummary | null>(null); const [alerts, setAlerts] = useState<Alert[]>([]); const [insights, setInsights] = useState<Insight[]>([]); const [records, setRecords] = useState<PatientRecord[]>([]); const [error, setError] = useState("");
  useEffect(() => { let cancelled = false; const load = async () => { try { const summary = await fetchDashboard(); if (!cancelled) setDashboard(summary); if (screen === "alerts") setAlerts(await fetchAlerts()); if (screen === "ai-insights") setInsights(await fetchInsights()); if (["history", "patient-history", "patterns", "regional-rankings"].includes(screen)) setRecords(await fetchRecords()); } catch (e) { if (!cancelled) setError(e instanceof Error ? e.message : "Unable to load uploaded data."); } }; void load(); return () => { cancelled = true; }; }, [screen]);
  if (error) return <main className="live-data-screen"><h1>Upload data to continue</h1><p>{error}</p><a href="#upload">Go to upload</a></main>;
  if (!dashboard) return <SkeletonScreen />;
  const titles: Record<string, string> = { dashboard: "Dashboard", alerts: "Alerts", "ai-insights": "AI Insights", history: "History", "patient-history": "Patients Registry", patterns: "Patterns & Trends", "surge-forecast": "Surge Forecast", "regional-rankings": "Regional Rankings" };
  const selected = screen === "ai-insights" ? JSON.parse(localStorage.getItem("d2a_selected_alert") || "null") as Alert | null : null;
  let content = <DashboardVisuals dashboard={dashboard} records={records} />;
  if (screen === "alerts") content = <AlertCards items={alerts} />; else if (screen === "ai-insights") content = <InsightCards items={insights} selectedAlert={selected} />; else if (screen === "patterns") content = <PatternsVisuals dashboard={dashboard} records={records} />; else if (screen === "surge-forecast") content = <ForecastCards forecasts={dashboard.district_forecasts} />; else if (screen === "regional-rankings") content = <RegionalRankingView records={records} />; else if (screen === "patient-history") content = <PatientRegistryView records={records} />; else if (screen === "history") content = <HistoryTimeline dashboard={dashboard} records={records} />;
  return <div className="app-shell"><Sidebar active={screen} /><main className="live-data-screen"><LiveTopbar title={titles[screen] ?? "Health Intelligence"} subtitle="Live results from your uploaded health center data" source={dashboard.active_data_source ?? "unknown"} /><div className="live-metrics"><Metric label="Visits" value={dashboard.total_visits} tone="blue" /><Metric label="Admissions" value={dashboard.total_admissions} tone="orange" /><Metric label="Active alerts" value={dashboard.active_alerts} tone="red" /><Metric label="Average wait" value={`${dashboard.average_wait_minutes} min`} tone="purple" /></div>{content}</main></div>;
}

function LiveTopbar({ title, subtitle, source }: { title: string; subtitle: string; source: string }) { const user = getUser(); const initials = (user?.name || "User").split(" ").map((part) => part[0]).join("").slice(0, 2).toUpperCase(); const date = new Intl.DateTimeFormat(undefined, { day: "numeric", month: "short", year: "numeric" }).format(new Date()); const goBack = () => { if (window.history.length > 1) window.history.back(); else window.location.hash = "dashboard"; }; return <header className="live-header"><div className="live-title-group"><div className="page-navigation"><button className="topbar-icon-button" onClick={goBack} title="Go back" aria-label="Go back"><ArrowLeft size={18} /></button><a className="topbar-icon-button" href="#dashboard" title="Go to dashboard" aria-label="Go to dashboard"><Home size={18} /></a></div><div><h1>{title}</h1><p>{subtitle}</p></div></div><div className="topbar-actions"><span className="source-badge">{source}</span><a className="notification-button" href="#alerts" aria-label="Open notifications"><Bell size={19} /></a><span className="date-display"><CalendarDays size={17} />{date}</span><span className="profile-circle" title={user?.name || "Signed-in user"}><CircleUser size={21} /><b>{initials}</b></span></div></header>; }

function SkeletonScreen() { return <div className="app-shell"><Sidebar active="dashboard" /><main className="live-data-screen"><header className="live-header"><div><div className="skeleton skeleton-title" /><div className="skeleton skeleton-subtitle" /></div><div className="topbar-actions"><div className="skeleton skeleton-status" /><div className="skeleton skeleton-icon" /><div className="skeleton skeleton-date" /><div className="skeleton skeleton-profile" /></div></header><div className="live-metrics">{["one", "two", "three", "four"].map((key) => <div className="live-metric skeleton-card" key={key}><div className="skeleton skeleton-label" /><div className="skeleton skeleton-value" /></div>)}</div><div className="skeleton-content-grid"><section className="chart-panel skeleton-card"><div className="skeleton skeleton-heading" /><div className="skeleton skeleton-chart" /></section><section className="chart-panel skeleton-card"><div className="skeleton skeleton-heading" /><div className="skeleton skeleton-chart" /></section><section className="live-list skeleton-card"><div className="skeleton skeleton-heading" />{[1, 2, 3, 4].map((row) => <div className="skeleton skeleton-row" key={row} />)}</section></div></main></div>; }

function Sidebar({ active }: { active: string }) { const links = [["dashboard", "Dashboard", LayoutDashboard], ["patient-history", "Patients Registry", Users], ["surge-forecast", "Surge Forecast", TrendingUp], ["alerts", "Alerts", Bell], ["ai-insights", "AI Insights", Brain], ["regional-rankings", "Regional Rankings", MapPinned], ["patterns", "Patterns", ChartNoAxesCombined], ["history", "History", History], ["settings", "Settings", Settings]] as const; const [count, setCount] = useState(0); const [menuOpen, setMenuOpen] = useState(false); useEffect(() => { void fetchAlerts().then((items) => setCount(items.length)).catch(() => setCount(0)); }, []); const closeMenu = () => setMenuOpen(false); return <><button className="mobile-menu-button" onClick={() => setMenuOpen(!menuOpen)} aria-label={menuOpen ? "Close navigation menu" : "Open navigation menu"} title={menuOpen ? "Close menu" : "Open menu"}>{menuOpen ? <X size={21} /> : <Menu size={21} />}</button>{menuOpen && <button className="sidebar-overlay" onClick={closeMenu} aria-label="Close navigation menu" /> }<aside className={`live-sidebar ${menuOpen ? "menu-open" : ""}`}><div className="drawer-header"><div className="live-logo"><HeartPulse size={27} strokeWidth={3} /> D2A<span>Health Intelligence</span></div><button className="drawer-close" onClick={closeMenu} aria-label="Close navigation menu" title="Close menu"><X size={19} /></button></div><nav>{links.map(([id, label, Icon]) => <a key={id} className={active === id ? "active" : ""} href={`#${id}`} onClick={closeMenu}><span className="nav-link-content"><Icon size={18} />{label}</span>{id === "alerts" && count > 0 && <b className="nav-badge">{count}</b>}</a>)}</nav><button onClick={() => { localStorage.clear(); window.location.hash = "login"; }}><LogOut size={17} />Log out</button></aside></>; }

function Metric({ label, value, tone }: { label: string; value: string | number; tone: string }) { const icons = { blue: Activity, orange: ClipboardList, red: TriangleAlert, purple: Timer }; const Icon = icons[tone as keyof typeof icons] || Activity; return <div className={`live-metric ${tone}`}><div className="metric-top"><span>{label}</span><i><Icon size={17} /></i></div><strong>{value}</strong><small>{tone === "red" ? "Requires review" : tone === "purple" ? "Current average" : "From uploaded data"}</small></div>; }
function LiveList({ title, items }: { title: string; items: string[] }) { return <section className="live-list"><h2>{title}</h2>{items.length ? <ul>{items.map((item, i) => <li key={`${item}-${i}`}>{item}</li>)}</ul> : <p>No results in the uploaded dataset.</p>}</section>; }
function DashboardOverview({ dashboard, records }: { dashboard: DashboardSummary; records: PatientRecord[] }) { const top = new Map<string, number>(); records.forEach((r) => top.set(r.village || r.district, (top.get(r.village || r.district) || 0) + r.visits)); return <div className="overview-grid"><LiveList title="Weekly patient volume" items={dashboard.weekly_volume.map((x) => `${x.week}: ${x.visits} visits`)} /><LiveList title="Cases by condition" items={dashboard.top_conditions.map((x) => `${x.condition}: ${x.visits} visits`)} /><LiveList title="Cases by village" items={[...top.entries()].sort((a, b) => b[1] - a[1]).map(([name, visits]) => `${name}: ${visits} visits`)} /><LiveList title="Overall status" items={[dashboard.active_alerts ? `${dashboard.active_alerts} active alerts require review.` : "Stable: no active alerts.", `Data source: ${dashboard.active_data_source}`]} /></div>; }
function AlertCards({ items }: { items: Alert[] }) { const open = (item: Alert) => { localStorage.setItem("d2a_selected_alert", JSON.stringify(item)); window.location.hash = "ai-insights"; }; return <section className="card-grid">{items.map((item) => <article className={`alert-panel ${item.severity}`} key={item.id} onClick={() => open(item)}><div className="panel-heading"><span className="severity">{item.severity}</span><span className="confidence">{Math.round(item.confidence * 100)}% confidence</span></div><h2>{item.title}</h2><p>{item.message}</p><div className="evidence"><strong>Evidence</strong>{item.evidence.join(" ")}</div><span className="alert-action">View AI mitigation →</span></article>)}</section>; }
function InsightCards({ items, selectedAlert }: { items: Insight[]; selectedAlert: Alert | null }) { return <section>{selectedAlert && <div className="alert-context"><strong>AI advice for: {selectedAlert.title}</strong><p>{selectedAlert.message}</p><span>{selectedAlert.evidence.join(" ")}</span></div>}<div className="card-grid">{items.map((item) => <article className="insight-panel" key={item.id}><div className="panel-heading"><span className="insight-heart"><HeartPulse size={20} /></span><span className="confidence">{Math.round(item.confidence * 100)}% confidence</span></div><h2>{item.title}</h2><p>{item.summary}</p><h3>Immediate mitigation</h3><ul>{item.considerations.map((x) => <li key={x}>{x}</li>)}</ul>{item.role_actions && <div className="role-actions">{Object.entries(item.role_actions).map(([role, actions]) => <div className="role-block" key={role}><h3>Advice for {role}</h3><ul>{actions.map((x) => <li key={x}>{x}</li>)}</ul></div>)}</div>}<div className="evidence"><strong>Evidence</strong>{item.evidence.join(" ")}</div></article>)}</div></section>; }
function PatternsView({ dashboard, records }: { dashboard: DashboardSummary; records: PatientRecord[] }) { return <><LiveList title="Cases over time" items={dashboard.weekly_volume.map((x) => `${x.week}: ${x.visits} visits`)} /><LiveList title="Cases by village" items={records.map((x) => `${x.village || x.district}: ${x.condition}, ${x.visits} visits`)} /></>; }
function ForecastView({ forecasts }: { forecasts: DashboardSummary["district_forecasts"] }) { return <LiveList title="Forecast by district" items={forecasts.map((x) => `${x.district}: ${x.current_visits} current, ${x.predicted_visits} predicted for ${x.next_week} (${x.lower_bound}-${x.upper_bound}), ${Math.round(x.confidence * 100)}% confidence`)} />; }
function RegionalRankingView({ records }: { records: PatientRecord[] }) { const values = new Map<string, number>(); records.forEach((x) => values.set(x.village || x.district, (values.get(x.village || x.district) || 0) + x.visits)); return <LiveList title="Affected villages" items={[...values.entries()].sort((a, b) => b[1] - a[1]).map(([name, visits], i) => `${i + 1}. ${name}: ${visits} visits`)} />; }
function PatientRegistryView({ records }: { records: PatientRecord[] }) { return <><AppendPatientData /><LiveList title="Patient registry" items={records.map((x) => `${x.record_id} - ${x.condition} - ${x.facility} - ${x.village || x.district}: ${x.visits} visits`)} /></>; }
function HistoryView({ dashboard, records }: { dashboard: DashboardSummary; records: PatientRecord[] }) { return <LiveList title="Reporting history" items={dashboard.weekly_volume.map((x) => `${x.week}: ${x.visits} visits`)} />; }

function DashboardVisuals({ dashboard, records }: { dashboard: DashboardSummary; records: PatientRecord[] }) { const max = Math.max(...dashboard.weekly_volume.map((x) => x.visits), 1); const points = dashboard.weekly_volume.map((x, i) => `${(i / Math.max(dashboard.weekly_volume.length - 1, 1)) * 100},${100 - (x.visits / max) * 82}`).join(" "); const conditions = dashboard.top_conditions.slice(0, 5); const total = Math.max(conditions.reduce((s, x) => s + x.visits, 0), 1); const locations = new Map<string, number>(); records.forEach((x) => locations.set(x.village || x.district, (locations.get(x.village || x.district) || 0) + x.visits)); return <div className="overview-grid"><section className="chart-panel weekly-panel"><div className="panel-title"><div><h2>Weekly patient volume</h2><p>Visits across uploaded records</p></div><span className="chart-key">● Live</span></div><div className="line-chart"><div className="chart-y"><span>{max}</span><span>{Math.round(max / 2)}</span><span>0</span></div><svg viewBox="0 0 100 100" preserveAspectRatio="none"><polygon className="trend-area" points={`0,100 ${points} 100,100`} /><polyline points={points} /></svg></div><div className="chart-labels">{dashboard.weekly_volume.map((x) => <span key={x.week}>{x.week}</span>)}</div></section><section className="chart-panel"><div className="panel-title"><div><h2>Cases by condition</h2><p>Share of reported visits</p></div></div><div className="condition-chart"><div className="donut" style={{ background: `conic-gradient(${conditions.map((x, i) => `${["#009e95", "#2563eb", "#f59e0b", "#8b5cf6", "#ef4444"][i]} ${(conditions.slice(0, i).reduce((s, y) => s + y.visits, 0) / total) * 100}% ${(conditions.slice(0, i + 1).reduce((s, y) => s + y.visits, 0) / total) * 100}%`).join(", ")})` }}><span>{conditions.length}</span></div><div className="legend">{conditions.map((x, i) => <span key={x.condition}><i style={{ background: ["#009e95", "#2563eb", "#f59e0b", "#8b5cf6", "#ef4444"][i] }} />{x.condition}<b>{x.visits}</b></span>)}</div></div></section><section className="chart-panel"><div className="panel-title"><div><h2>Cases by village</h2><p>Highest visit locations</p></div></div><div className="village-bars">{[...locations.entries()].sort((a, b) => b[1] - a[1]).slice(0, 5).map(([name, visits]) => <div className="village-bar" key={name}><div><strong>{name}</strong><span>{visits}</span></div><div className="bar-track"><i className="bar-color color-0" style={{ width: `${(visits / Math.max(...locations.values(), 1)) * 100}%` }} /></div></div>)}</div></section><section className="status-panel"><span className="status-icon warning">●</span><div><h2>Overall status</h2><strong>{dashboard.active_alerts ? "Needs attention" : "Stable"}</strong><p>{dashboard.active_alerts} active alerts from uploaded data.</p></div><a href="#alerts">Review alerts</a></section></div>; }

function PatternsVisuals({ dashboard, records }: { dashboard: DashboardSummary; records: PatientRecord[] }) { const weekly = dashboard.weekly_volume; const max = Math.max(...weekly.map((x) => x.visits), 1); const points = weekly.map((x, i) => `${(i / Math.max(weekly.length - 1, 1)) * 100},${100 - (x.visits / max) * 82}`).join(" "); return <div className="patterns-grid"><section className="chart-panel"><div className="panel-title"><div><h2>Cases over time</h2><p>Weekly reporting trend from uploaded data</p></div><span className="chart-key">● Live data</span></div>{weekly.length ? <><div className="line-chart"><div className="chart-y"><span>{max}</span><span>{Math.round(max / 2)}</span><span>0</span></div><svg viewBox="0 0 100 100" preserveAspectRatio="none" aria-label="Cases over time"><line x1="0" y1="18" x2="100" y2="18" /><line x1="0" y1="59" x2="100" y2="59" /><line x1="0" y1="100" x2="100" y2="100" /><polygon className="trend-area" points={`0,100 ${points} 100,100`} /><polyline points={points} /></svg></div><div className="chart-labels">{weekly.map((x) => <span key={x.week}>{x.week}</span>)}</div></> : <p>No weekly data is available yet.</p>}</section><section className="chart-panel"><div className="panel-title"><div><h2>Cases by village</h2><p>Visits grouped by reporting location</p></div></div><LiveList title="" items={records.map((x) => `${x.village || x.district}: ${x.visits} visits`)} /></section></div>; }

function ForecastCards({ forecasts }: { forecasts: DashboardSummary["district_forecasts"] }) { return <section className="forecast-panel"><div className="panel-title"><div><h2>Forecast by district</h2><p>Next-period projections for every ingested area</p></div><span className="chart-key">● Live data</span></div><div className="forecast-grid">{forecasts.map((x) => <article className={`forecast-card ${x.trend_direction}`} key={x.district}><div className="panel-heading"><h3>{x.district}</h3><span className="confidence">{Math.round(x.confidence * 100)}% confidence</span></div><span className="forecast-trend">{x.trend_direction}</span><div className="forecast-values"><div><small>Current</small><strong>{x.current_visits}</strong></div><div><small>{x.next_week}</small><strong>{x.predicted_visits}</strong></div><div><small>Range</small><strong>{x.lower_bound}-{x.upper_bound}</strong></div></div></article>)}</div></section>; }

function HistoryTimeline({ dashboard, records }: { dashboard: DashboardSummary; records: PatientRecord[] }) { return <section className="history-panel"><div className="panel-title"><div><h2>Reporting history</h2><p>Weekly visits and admissions from uploaded records</p></div></div><div className="history-timeline">{dashboard.weekly_volume.slice().reverse().map((x, i) => <article className="history-event" key={x.week}><span className={`timeline-dot ${i === 0 ? "current" : ""}`} /><div><strong>{x.week}</strong><p>{x.visits} visits reported</p><span>{i === 0 ? "Latest reporting period" : "Previous reporting period"}</span></div></article>)}</div><div className="history-summary"><strong>{records.length}</strong><span>uploaded records across {new Set(records.map((x) => x.facility)).size} facilities</span></div></section>; }

function AppendPatientData() { const [file, setFile] = useState<File | null>(null); const [message, setMessage] = useState(""); const [loading, setLoading] = useState(false); async function submit(e: FormEvent) { e.preventDefault(); if (!file || loading) return; setLoading(true); try { const result = await appendPatientCsv(file, getUser()?.email); setMessage(`${result.accepted_records} new records added.`); setTimeout(() => window.location.reload(), 500); } catch (error) { setMessage(error instanceof Error ? error.message : "Upload failed."); setLoading(false); } } return <form className="append-data" onSubmit={submit}><strong>Add patient visit data</strong><input type="file" accept=".csv,text/csv" onChange={(e) => setFile(e.target.files?.[0] || null)} required disabled={loading} /><button disabled={!file || loading}>{loading ? <><Spinner />Uploading...</> : "Add CSV"}</button>{message && <span>{message}</span>}</form>; }

function SettingsScreen() { const user = getUser(); const [connection, setConnection] = useState("Checking..."); const [alerts, setAlerts] = useState<Alert[]>([]); useEffect(() => { void fetchHealth().then(() => setConnection("Backend connected")).catch(() => setConnection("Backend unavailable")); void fetchAlerts().then(setAlerts).catch(() => setAlerts([])); }, []); return <div className="app-shell"><Sidebar active="settings" /><main className="live-data-screen settings-screen"><LiveTopbar title="Settings" subtitle="Manage your account and live intelligence notifications" source={connection} /><section className="settings-card"><h2>Profile information</h2><p>Signed-in account and health centre connection.</p><div className="profile-grid"><ProfileValue label="Full name" value={user?.name || "Not available"} /><ProfileValue label="Email address" value={user?.email || "Not available"} /><ProfileValue label="Role" value={user?.role || "Not available"} /><ProfileValue label="Health centre" value={user?.health_center || "Not available"} /><ProfileValue label="Dataset status" value={user?.dataset_ready ? "Ready" : "Upload required"} /></div></section><section className="settings-card"><h2>Notifications</h2><p>Live alerts from your uploaded dataset.</p><p className="notification-summary"><strong>{alerts.length}</strong> active notifications <a href="#alerts">Review alerts</a></p></section></main></div>; }
function ProfileValue({ label, value }: { label: string; value: string }) { return <div className="profile-value"><span>{label}</span><strong>{value}</strong></div>; }
function SignupScreen() { const [form, setForm] = useState({ name: "", email: "", password: "", health: "" }); const [showPassword, setShowPassword] = useState(false); const [loading, setLoading] = useState(false); const [error, setError] = useState(""); async function submit(e: FormEvent) { e.preventDefault(); if (loading) return; setLoading(true); setError(""); try { const response = await signup(form.name, form.email, form.password, form.health); localStorage.setItem("d2a_access_token", response.access_token); localStorage.setItem("d2a_user", JSON.stringify(response.user)); window.location.hash = "upload"; } catch (requestError) { setError(requestError instanceof Error ? requestError.message : "Unable to create account."); setLoading(false); } } return <main className="auth-layout"><section className="auth-branding"><HeartPulse size={58} /><h1>Every patient record holds a story.</h1><p>D2A turns health data into early, meaningful signals.</p></section><form className="auth-form" onSubmit={submit}><h2>Create your account</h2><input placeholder="Full name" value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} required disabled={loading} /><input type="email" placeholder="Email address" value={form.email} onChange={(e) => setForm({ ...form, email: e.target.value })} required disabled={loading} /><input placeholder="Health centre" value={form.health} onChange={(e) => setForm({ ...form, health: e.target.value })} required disabled={loading} /><div className="password-field"><input type={showPassword ? "text" : "password"} minLength={8} placeholder="Password" value={form.password} onChange={(e) => setForm({ ...form, password: e.target.value })} required disabled={loading} /><button type="button" className="password-toggle" onClick={() => setShowPassword(!showPassword)} title={showPassword ? "Hide password" : "Show password"} aria-label={showPassword ? "Hide password" : "Show password"}>{showPassword ? <EyeOff size={18} /> : <Eye size={18} />}</button></div><PasswordGuidance password={form.password} />{error && <p className="form-error">{error}</p>}<button disabled={loading}>{loading ? <><Spinner />Creating account...</> : "Create account"}</button><a href="#login">Back to login</a></form></main>; }
function PasswordGuidance({ password }: { password: string }) { const checks = [{ label: "At least 8 characters", valid: password.length >= 8 }, { label: "One uppercase letter", valid: /[A-Z]/.test(password) }, { label: "One number", valid: /\d/.test(password) }, { label: "One special character", valid: /[^A-Za-z0-9]/.test(password) }]; if (!password || checks.every((check) => check.valid)) return null; return <div className="password-guidance" role="status"><strong>Make your password stronger</strong><ul>{checks.filter((check) => !check.valid).map((check) => <li key={check.label}>{check.label}</li>)}</ul></div>; }
function LoginScreen() { const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [showPassword, setShowPassword] = useState(false); const [loading, setLoading] = useState(false); const [error, setError] = useState(""); async function submit(e: FormEvent) { e.preventDefault(); if (loading) return; setLoading(true); setError(""); try { const response = await login(email, password); localStorage.setItem("d2a_access_token", response.access_token); localStorage.setItem("d2a_user", JSON.stringify(response.user)); localStorage.removeItem("d2a_has_uploaded_data"); window.location.hash = response.requires_data_upload ? "upload" : "dashboard"; } catch (requestError) { setError(requestError instanceof Error ? requestError.message : "Unable to sign in."); setLoading(false); } } return <main className="auth-layout"><section className="auth-branding"><HeartPulse size={58} /><h1>Every patient record holds a story.</h1><p>D2A turns health data into early, meaningful signals.</p></section><form className="auth-form" onSubmit={submit}><h2>Welcome back</h2><p>Sign in to continue to your account</p><input type="email" placeholder="Staff ID or Email" value={email} onChange={(e) => setEmail(e.target.value)} required disabled={loading} /><div className="password-field"><input type={showPassword ? "text" : "password"} placeholder="Password" value={password} onChange={(e) => setPassword(e.target.value)} required disabled={loading} /><button type="button" className="password-toggle" onClick={() => setShowPassword(!showPassword)} title={showPassword ? "Hide password" : "Show password"} aria-label={showPassword ? "Hide password" : "Show password"}>{showPassword ? <EyeOff size={18} /> : <Eye size={18} />}</button></div><a className="auth-forgot-link" href="#forgot-password">Forgot password?</a>{error && <p className="form-error">{error}</p>}<button disabled={loading}>{loading ? <><Spinner />Signing in...</> : "Sign in"}</button><a href="#signup">New to D2A? Create an account</a></form></main>; }
function UploadScreen() { const [file, setFile] = useState<File | null>(null); const [loading, setLoading] = useState(false); const [error, setError] = useState(""); async function submit(e: FormEvent) { e.preventDefault(); if (!file || loading) return; setLoading(true); setError(""); try { const result = await uploadPatientCsv(file, getUser()?.email); if (result.accepted_records) { localStorage.setItem("d2a_has_uploaded_data", "true"); window.location.hash = "dashboard"; } } catch (requestError) { setError(requestError instanceof Error ? requestError.message : "Upload failed."); setLoading(false); } } return <main className="auth-layout"><section className="auth-branding"><HeartPulse size={58} /><h1>Start with your health centre data.</h1><p>Upload an anonymized CSV to activate trends, alerts, and AI recommendations.</p></section><form className="auth-form" onSubmit={submit}><h2>Upload your first dataset</h2><input type="file" accept=".csv,text/csv" onChange={(e) => setFile(e.target.files?.[0] || null)} required disabled={loading} />{error && <p className="form-error">{error}</p>}<button disabled={!file || loading}>{loading ? <><Spinner />Uploading...</> : "Upload and continue"}</button></form></main>; }

function Spinner() { return <LoaderCircle className="button-spinner" size={17} aria-hidden="true" />; }

function ForgotPasswordScreen() { const [email, setEmail] = useState(""); const [loading, setLoading] = useState(false); const [message, setMessage] = useState(""); const [code, setCode] = useState(""); const [error, setError] = useState(""); async function submit(e: FormEvent) { e.preventDefault(); if (loading) return; setLoading(true); setError(""); try { const result = await requestPasswordReset(email); sessionStorage.setItem("d2a_reset_email", email); if (result.development_code) { sessionStorage.setItem("d2a_reset_code", result.development_code); setCode(result.development_code); } setMessage(result.message); } catch (requestError) { setError(requestError instanceof Error ? requestError.message : "Unable to send reset code."); } finally { setLoading(false); } } return <main className="auth-layout"><section className="auth-branding"><HeartPulse size={58} /><h1>Get back to your health intelligence.</h1><p>We will help you securely reset your D2A account password.</p></section><form className="auth-form" onSubmit={submit}><h2>Forgot password?</h2><p>Enter your account email and we will send you a reset code.</p><input type="email" placeholder="Email address" value={email} onChange={(e) => setEmail(e.target.value)} required disabled={loading} />{message && <div className="reset-message"><strong>Reset code requested</strong><span>{message}</span>{code && <b>Development code: {code}</b>}</div>}{error && <p className="form-error">{error}</p>}<button disabled={loading}>{loading ? <><Spinner />Sending code...</> : "Send reset code"}</button><a href="#reset-password">I already have a code</a><a href="#login">Back to login</a></form></main>; }

function ResetPasswordScreen() { const [email, setEmail] = useState(() => sessionStorage.getItem("d2a_reset_email") || ""); const [code, setCode] = useState(() => sessionStorage.getItem("d2a_reset_code") || ""); const [password, setPassword] = useState(""); const [showPassword, setShowPassword] = useState(false); const [loading, setLoading] = useState(false); const [message, setMessage] = useState(""); const [error, setError] = useState(""); async function submit(e: FormEvent) { e.preventDefault(); if (loading) return; setLoading(true); setError(""); try { const result = await resetPassword(email, code, password); sessionStorage.removeItem("d2a_reset_email"); sessionStorage.removeItem("d2a_reset_code"); setMessage(result.message); setTimeout(() => { window.location.hash = "login"; }, 1200); } catch (requestError) { setError(requestError instanceof Error ? requestError.message : "Unable to reset password."); } finally { setLoading(false); } } return <main className="auth-layout"><section className="auth-branding"><HeartPulse size={58} /><h1>A secure next step.</h1><p>Use the code you received to choose a new password for your D2A account.</p></section><form className="auth-form" onSubmit={submit}><h2>Reset your password</h2><p>Enter the six-digit code and create a new password.</p><input type="email" placeholder="Email address" value={email} onChange={(e) => setEmail(e.target.value)} required disabled={loading} /><input inputMode="numeric" pattern="[0-9]{6}" maxLength={6} placeholder="6-digit reset code" value={code} onChange={(e) => setCode(e.target.value.replace(/\D/g, ""))} required disabled={loading} /><div className="password-field"><input type={showPassword ? "text" : "password"} minLength={8} placeholder="New password" value={password} onChange={(e) => setPassword(e.target.value)} required disabled={loading} /><button type="button" className="password-toggle" onClick={() => setShowPassword(!showPassword)} title={showPassword ? "Hide password" : "Show password"} aria-label={showPassword ? "Hide password" : "Show password"}>{showPassword ? <EyeOff size={18} /> : <Eye size={18} />}</button></div><PasswordGuidance password={password} />{message && <p className="form-success">{message}</p>}{error && <p className="form-error">{error}</p>}<button disabled={loading}>{loading ? <><Spinner />Resetting password...</> : "Reset password"}</button><a href="#login">Back to login</a></form></main>; }
